name       : python-hatchling
version    : 1.5.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/h/hatchling/hatchling-1.5.0.tar.gz : 9ca409a41140cc662164680b78adcd3ba77b23a945984bd9970d11fe38e86a38
homepage   : https://github.com/pypa/hatch
license    : MIT
component  : programming.python
summary    : Modern, extensible Python project management
description: |
    Hatch is a modern, extensible Python project manager.
builddeps  :
    - python-build
    - python-editables
    - python-installer
    - python-packaging
    - python-pathspec
    - python-pluggy
rundeps    :
    - python-editables
    - python-packaging
    - python-pathspec
    - python-pluggy
    - python-tomli
build      : |
    %python3_setup
install    : |
    %python3_install
