name       : python-hatchling
version    : 1.6.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/h/hatchling/hatchling-1.6.0.tar.gz : bd6e8505de511ac4217ff50927f6d1845494608e401e63a62b830c31fb613544
homepage   : https://github.com/pypa/hatch
license    : MIT
component  : programming.python
summary    : Modern, extensible Python project management
description: |
    Hatch is a modern, extensible Python project manager.
builddeps  :
    - python-build
    - python-editables
    - python-installer
    - python-packaging
    - python-pathspec
    - python-pluggy
rundeps    :
    - python-editables
    - python-packaging
    - python-pathspec
    - python-pluggy
    - python-tomli
build      : |
    %python3_setup
install    : |
    %python3_install
